spring.application.name=Buyzen
spring.datasource.url=jdbc:mysql://localhost:3306/buyzen
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey="RK1cn2Uthl7AM7+JKFM/bfkjqXmEslRm2Kwhte/v1k4="