spring.application.name=HibernateTest
spring.datasource.url=jdbc:postgresql://ep-frosty-star-aiizu5f8-pooler.c-4.us-east-1.aws.neon.tech/hibernate?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FQBIeLlGn0A5

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true